### ISSUE TITLE
offline capabilities and auto-syncing

### ISSUE THREAD

**Issue by marqueeeeeee** [parse-community/Parse-SDK-Flutter#149]
Does this support offline saving and auto-sync when network is available? similar to saveEventually from parse sdk and firebase db? Thank you!

**Comment by rodrigosmarques** [comment]
Hi @marqueeeeeee,
this feature is not available yet.

**Comment by frsisalima** [comment]
Hello, is the implementation of this feature planned? it would be great to have offline support

**Comment by monajafi** [comment]
we can implement saveEventually in android by caching saves if there is no connectivity then with help of workmanager plugin which is a wrapper around android WorkManager we can sync the cached saves when the device connects to internet
This is easy in android but I'm trying to figure out how to implement in iOS because the background jobs are restricted in iOS we have just background fetch.
One point to have in mind about saveEventually is that there is no callback after saving 
I have an app which is developed using native sdk If the server is down and device get connected to internet the save would fail

**Comment by phillwiggins** [comment]
Hey Noida

We should stick to keeping it pure Dart.

We simply need a connection manager and a save pool of objects.

**Comment by monajafi** [comment]
One important thing is that after successful save the save pool should be cleared not just after gaining connectivity and saving without considering the save result, which is a behaviour in native sdks

**Comment by phillwiggins** [comment]
100% correct logic. We only clear the pool, once confirmed successfully
saved.

I was looking at this but in the past few months been too busy to implement.

**Comment by cadaniel** [comment]
Would love to see this feature. It's basically all I'm missing from what I need to replace firebase in my app (hopefully before launching)

Is there some engineering docs for this that I could help contribute?

**Comment by RodrigoSMarques** [comment]
The project is using SEMBAST which is also a NoSQL database written in Dart.
The sample application is using SEMBAST to do some offline resources. Take a look at the sample project.

You can study the source of Parse SDK on Android to see how it works. This is how I contributed to this plugin.

**Comment by Sun3** [comment]
I also would love to see saveEventually implemented for both Android and iOS.

**Comment by allanwolski** [comment]
It's very important to have offline support for our application.

**Comment by visual-velocity** [comment]
> It's very important to have offline support for our application.

I agreed

**Comment by paulocagol** [comment]
Hello, any progress?

**Comment by RodrigoSMarques** [comment]
No progress.

**Comment by RodrigoSMarques** [comment]
No progress.

**Comment by paulocagol** [comment]
Okay, thanks for the feedback.

**Comment by 2shrestha22** [comment]
We need this feature. I moved from Firebase to Parse because it is a great OSS. But while migrating my app I have feeling of using other platform like Appwrite because this SDK is very parse specific. I mean why we need to use get set instead we can do it in simple dart way using constructors and ability to use freezed package to create data class will be great.

I haven't yet understood the usage of clone() in the SDK. I hope I can contribute to this awesome SDK in future.

**Comment by sils** [comment]
For others looking here, this approach seems interesting, though it involves ditching the SDK sadly: https://www.back4app.com/docs/flutter/graphql/offline-first-database

**Comment by sils** [comment]
Nice!

**Comment by pastordee** [comment]
I Loved this feature from my objective C days nice one.
