### ISSUE TITLE
Remove _unsavedChanges from custom User

### ISSUE THREAD

**Issue by nicoco2** [parse-community/Parse-SDK-Flutter#318]
When i get a locally saved User with my custom class `ParseUser.currentUser(customUserObject: CustomUser.empty())` the field _unsavedChanges gets populated, because a new object gets created and when the fields are set they are added to `_unsavedChanges`. This results in overriding the changes that were made on the server when calling `customUserObject.getUpdatedUser();`. 

Is it possible to get a public method like `parseObject.clearUnsavedChanges()` or to call `_unsavedChanges.clear()`  in `parseUser.getUpdatedUser()`?

**Comment by maaeps** [comment]
@nicoco2 
I just pushed a branch with such a clearUnsavedChanges methode https://github.com/maaeps/Parse-SDK-Flutter/tree/clearUnsavedChanges.

Could you test it with your issue?

**Comment by nicoco2** [comment]
Thanks, now it works.

**Comment by maaeps** [comment]
@nicoco2 
This feature was merged to [release/1.0.26](https://github.com/parse-community/Parse-SDK-Flutter/tree/release/1.0.26).
You might want to change your dependencies to use this branch now, in order to receive further additions and changes to the SDK.

(If there are no more questions at the moment, please close this issue.)
