### ISSUE TITLE
Create User with Username and Password Only 

### ISSUE THREAD

**Issue by podcoder** [parse-community/Parse-SDK-Flutter#465]
I would like to signup a user with `username` and `password` only.
But, if I extend the `ParseUser` class, I need to pass three parameters i.e username, password and email.
```dart
class TestUser extends ParseObject implements ParseCloneable {
  TestUser() : super("_User");
  TestUser.clone() : this();

  @override
  TestUser clone(Map<String, dynamic> map) => TestUser.clone()..fromJson(map);

  static const String keyUsername = "username";
  static const String keyPassword = "password";

  String get username => get<String>(keyUsername);
  set username(String username) => set<String>(keyUsername, username);

  String get password => get<String>(keyPassword);
  set password(String password) => set<String>(keyPassword, password);
}
```

I was able to achieve the functionality I want as follow:
```dart
  Future _createUser() async {
    var user = TestUser()..set('username', 'sky12')..set('password', '123456');
    await user.save();
  }
```

I was wondering if there is a better approach to accomplish this task by extending `ParseUser` class. Because it will enable me to take full advantages of already implement functionalities.

**Comment by fischerscode** [comment]
I thought, setting an email is required in order to create a user on the parse server.
But it seems like it is optional, as creating a new user without an email works from the dashboard.

I recommend you to extend your custom class on `ParseUser` and not on `ParseObject`.
In the constructor you can set email to `null`.

The only problem is, that this SDK does currently not support running the `signUp()` function without and email address due to [this](https://github.com/parse-community/Parse-SDK-Flutter/blob/2088bf1b07594a080b91d5002eda0515dae63568/lib/src/objects/parse_user.dart#L150) if-block. (`login()` works)

As a workaround you can either provide a dummy email (like `user@example.com`) or you create the new user first and login afterwards.
