### ISSUE TITLE
2.0.1 has no CoreStoreSharedPrefsImp

### ISSUE THREAD

**Issue by vernalclareai** [parse-community/Parse-SDK-Flutter#512]
Hi, I have installed the parse_server_sdk: ^2.0.1 today.
but CoreStoreSharedPrefsImp is not resolved to compile the project.
Any issue on this?
Thanks.

**Comment by LavTeamProject** [comment]
may be:
parse_server_sdk**_flutter**: ^2.0.0

**Comment by vernalclareai** [comment]
I tried with the parse_server_sdk_flutter: ^2.0.0, but getting issue when launching the app from the source code.

-Error Log:
Launching lib\main.dart on Custom Tablet in debug mode...
Running Gradle task 'assembleDebug'...
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectivity:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 37s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by LavTeamProject** [comment]
1) flutter pub cache repair
2) flutter clean
3) restart Android Studio

**Comment by vernalclareai** [comment]
Hi, the issue is same.

**Comment by fischerscode** [comment]
You've run `flutter pub get` right?

**Comment by vernalclareai** [comment]
yes, done flutter pub get
Sample project on the github also has the launch issue.
Can you try?

**Comment by fischerscode** [comment]
For me, the example app of the master branch worked in the android and ios emulator.
I think, it's some cache issue. Maybe a grandle issue and properly related to [this](https://github.com/flutter/flutter/issues/58974).
I happens when using a android emulator, right?

Maybe deleting the android folder and `running flutter create .` helps. (You should only try this with the example application. Not with your project.)

**Comment by vernalclareai** [comment]
yes, happened with android emulator.

**Comment by vernalclareai** [comment]
then to use the lib on my project, what is the solution?

**Comment by fischerscode** [comment]
> Maybe deleting the android folder and running flutter create . helps. (You should only try this with the example application. Not with your project.)

Did this work for the example project?

**Comment by vernalclareai** [comment]
Still not try on your example project.
If it is working on your example project by recreating the folder, what is the solution on my project?
Thanks for your guide.

**Comment by fischerscode** [comment]
If it works, then the solution might be:
1. backup android folder
2. delete it
3. `flutter create .`
4. give it a try
5. then merge the  backup folder into the new one

**Comment by InTheClodus** [comment]
The document is changed to this sentence 
`coreStore: await CoreStoreSembastImp.getInstance("/data")`
or
`coreStore: CoreStoreMemoryImp()`  One of the comments // Non persistent mode (default): Sdk will store everything in memmore instead of using Sembast as an internal DB.

If you want to persist the user should use  `coreStore: await CoreStoreSembastImp.getInstance("/data")`

But when I use `coreStore: await CoreStoreSembastImp.getInstance("/data")` this line of code, the initialization fails, I don't know if you solved it,

If it is solved, please tell me how to solve it, thank you

**Comment by monster555** [comment]
On pubspec.yaml:
`path_provider: ^1.6.14`
Then import it on the same file that you initialize Parse:
`import 'package:path_provider/path_provider.dart';`
Add this before calling Parse.initialize:
`Directory appDocDir = await getApplicationDocumentsDirectory();`
And then change your coreStore to:
`coreStore: await CoreStoreSembastImp.getInstance(appDocDir.path + "/data"),`

**Comment by RodrigoSMarques** [comment]
We are closing issues that have been open for a long time without activity. 
This will make it easier to organize things from now on.
If the problem persists, please open a new issue.
Thanks.
