### ISSUE TITLE
Update event on LiveList

### ISSUE THREAD

**Issue by gcostaapps** [parse-community/Parse-SDK-Flutter#607]
Hi, 

First I want to thank you for maintaning this great library.

I'm developing a live query funtionality and I faced the ParseLiveListWidget, although it provides live query functionalities it mixes presentation code with logic.

There is a way to update the objects listening to the LiveList stream but right now when a object is updated it doesn't send a event, only for creating and deleting objects.

I solved this issue adding the ParseLiveListUpdateEvent. I've already submited a pr to resolve this.  PR #606 

If you can review it and merge I think it would benefit people like me who doesn't want to mix logic with presentation.

(I'm using the null-safety branch)

**Comment by fischerscode** [comment]
I am not sure if this solves your problem, but back when coding the `ParseLiveList` part, I intended the `ParseLiveListElement` to handle in object updates.

But as it should be fully compatible adding you additional Event might be a good idea in order to give developers more options.

I will have a look at your PR soon.

**Comment by fischerscode** [comment]
I've merged your PR, thanks for your contribution.
