### ISSUE TITLE
package connectivity_plus is old

### ISSUE THREAD

**Issue by sgehrman** [parse-community/Parse-SDK-Flutter#992]
you have: connectivity_plus: ^5.0.2

latest is:   connectivity_plus: ^6.0.1

**Comment by chadpav** [comment]
@mtrezza I might be confused buy I don't think this should have been closed since `connectivity_plus` was not updated to latest. I'm wrapping up a PR that addresses this in #1001 

CC: @sgehrman - there was a breaking change in the latest version of connectivity_plus so this was not a straightforward dependency bump.
